#!/usr/bin/python
import os
import email
import argparse
from email.utils import getaddresses

def extract_and_format(headers):
    hdrs = []
    for header in headers:
        hdrs.append(msg.get_all(header,[]))
    flat = [item for sublist in hdrs for item in sublist] 
    return getaddresses(flat)

parser = argparse.ArgumentParser(description='Extract e-mail headers')

parser.add_argument('filename', metavar='<FILENAME>', nargs=1,
        help='file to process')

parser.add_argument('--addr', metavar='To/Cc/From/resent-to', 
        help='an address header, will be post processed and stripped')

#make it support a  comma separated list of headers to extract
parser.add_argument('--hdr', metavar='HEADER-STRING', 
        help='extracts a raw header from the file')

args = parser.parse_args()

msg = email.message_from_file(open(args.filename[0]))

if args.addr :
    addresses = extract_and_format(args.addr.split(','))
    print " ".join(map(lambda x: x[1],addresses))

if args.hdr:
    hdrs = args.hdr.split(',')
    for h in hdrs:
        print " ".join(msg.get_all(h))
    
# no arguments supplied, dump all headers but remove \n\t from data and truncate to fit terminal
if not args.hdr and not args.addr:
    rows, columns = os.popen('stty size', 'r').read().split()
    p2w = int(columns) - ( 25 + 3 )
    for item in msg.items():
        print "{0:25} : {1:60}".format(item[0],item[1].replace("\n\t","")[:p2w])

